# 文件路径 .github/workflows/deployment.yml
name: Deployment

on:
  push:
    branches: [hexo] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'





    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        npm install -g gulp
        npm install --save
        npm i gulp-replace --save
        hexo clean
        hexo g
        gulp

    - name: Deploy to Github Pages
      env:
        GIT_NAME: LeeSinGOST
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/LeeSinGOST/LeeSinGOST.github.io
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:master

    